image: node:16.14-alpine

cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy_staging
  - deploy_production

# Job 1:
Init:
  stage: init
  script:
    - yarn install
  only:
    - development
    - main

#Job 2:
staging:
    stage: deploy_staging
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - development

#Job 2:
production:
    stage: deploy_production
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - main
